### ISSUE TITLE
something went wrong when saving your file

### ISSUE THREAD

**Issue by Wasabi72** [fredl99/YOURLS-Upload-and-Shorten#1]
Hi,
for a few days the Plugin does not work anymore.
I always get the error: “something went wrong when saving your file“.
Nothing was changed to the Plugin-Code.
Does anyone have an idea where the error might be…
It ran so far without problems?

Thx
(Sorry for my bad English)

**Comment by fredl99** [comment]
Hi @Wasabi72,
Sorry for the delayed answer!

This message only appears when PHP couldn't successfully move the uploaded file to its final destination/filename. See the [description of this function](http://php.net/manual/en/function.move-uploaded-file.php).
So the cause might be somewhere in your PHP setup or even on the server itself. Maybe the file-paths changed or there is insufficient space or anything like that.

Could you check your server's logfiles and report back, please?

BTW:

> It ran so far without problems

Nice to read that :smiley:

**Comment by fredl99** [comment]
@Wasabi72
No response within almost one month. 
I assume the problem is solved and this issue can be closed?

**Comment by fredl99** [comment]
Closed due to inactivity.

Feel free to re-open it if the problem comes back again.
