### ISSUE TITLE
Upload failed, sorry! The error was 1

### ISSUE THREAD

**Issue by rubella** [fredl99/YOURLS-Upload-and-Shorten#10]
I'm trying to upload a 2.3 MB pdf. Other, larger pdfs work normally. I'm not sure what the error above means. There is no real indication in the logs.Any ideas?

**Comment by fredl99** [comment]
Hi,
The plugin only forwards the error codes of the PHP upload function. A value of "1" is defined as `The uploaded file exceeds the upload_max_filesize directive in php.ini. `
So you should investigate this setting first. Remember that PHP can load different php.ini files, too.
At the moment I couldn't explain why larger files wouldn't cause the same error. So please look at your php.ini first, then we can dig deeper.

**Comment by fredl99** [comment]
After 2-1/2 months without feedback I think it's time to close this issue. Feel free to re-open if the problem persits.
