### ISSUE TITLE
Short URL not shown or available

### ISSUE THREAD

**Issue by MrMyles** [fredl99/YOURLS-Upload-and-Shorten#11]
Installed, configured and activated plugin.
Uploads work perfectly. Direct URL shows and works perfectly.
Short URL does not work at all in this plugin.

No matter what I choose for a custom shortname it never gets applied to the upload link and never gets shown below the direct URL. If I manually type in the shortname I chose it does not work.

All other features/settings work perfectly both in the plugin and the YOURLs system as a whole.
![2018-03-07_1157](https://user-images.githubusercontent.com/37154707/37109215-e8c9c94c-21fe-11e8-9a2b-7d7c8ce5afc4.png)

**Comment by MrMyles** [comment]
Ignore. Issue was with another plugin checking valid URL's. Disabled that plugin and all works perfectly.

**Comment by fredl99** [comment]
Many thanks for the input.
Could you please specify that other plugin? Maybe I should mention that in the docs.
Thanks again,
Fredl.

**Comment by MrMyles** [comment]
Check URL 1.1

**Comment by fredl99** [comment]
Thanks again for your input. I'll add this info to the docs someday.
Think it's time to close this issue now.
