### ISSUE TITLE
Error Uploading Big Size File

### ISSUE THREAD

**Issue by lookatdons** [fredl99/YOURLS-Upload-and-Shorten#18]
I was trying to upload like 267mb file size, but when it reached 50% upload the website became blank. Tried to redo it but the same result, and it always happen every 50% upload. Please advice. Thank you.

**Comment by fredl99** [comment]
Hi,
The file upload is done by calling a standard PHP function. 
This sounds like a common issue. Most likely you might have to tweak your php.ini. Look here to see what you can do: https://stackoverflow.com/questions/578190/can-file-uploads-time-out-in-php

Let me know if that helps.
Regards,
Fredl

**Comment by fredl99** [comment]
No more comments means you found a solution, I guess. 
So I close this issue. Feel free to re-open if I was wrong.
