### ISSUE TITLE
Forbidden Error

### ISSUE THREAD

**Issue by jboutros89** [fredl99/YOURLS-Upload-and-Shorten#21]
Hello,

I installed the plugin based on your documentation, the upload was successful, however when i try to visit the shortened link (go.mydomain.com/aaa), i am faced with a Forbidden Error. The case is the same if i follow the Long URL (go.mydomain.com/uploadedfile.txt)

Note: I have created a new folder named uploaddir (on the same level of the admin and images folders). I set the permission properly and the ownership to www-data user and group.

Note2: I am able to access the file if i go to (go.mydomain/uploaddir/uploadedfile.txt)

What do you think would be the case?

Thanks

**Comment by fredl99** [comment]
Hi,

Did you define the SHARE_URL as
`define( 'SHARE_URL', 'https://go.mydomain.com/uploaddir/' );` ?

**Comment by fredl99** [comment]
According to your note #2 this is the place where the file resides, so that's where YOURLS should fetch it. Or better said, where it should redirect the client to...

**Comment by jboutros89** [comment]
Yes, exactly, this is the way i configured it. (but not HTTPS, HTTP)

**Comment by fredl99** [comment]
Hmm..
After a successful upload the plugin shows both, the short and the long URL. Is the second one the same as the one you can access directly?

**Comment by fredl99** [comment]
Both are clickable links, btw.

**Comment by fredl99** [comment]
After modifying your config file it might help to restart your PHP instance. It might also be sufficient to toggle the activation of the plugin in order to reload the config.

**Comment by jboutros89** [comment]
Oh it worked mate, Thank you, seems restarting the web service was the issue.

Much appreciated!

**Comment by fredl99** [comment]
I'm glad I could help you. Have fun!
