### ISSUE TITLE
Question: Amazon S3

### ISSUE THREAD

**Issue by JayHoltslander** [fredl99/YOURLS-Upload-and-Shorten#3]
Can this be used to upload to an Amazon S3 bucket?

**Comment by fredl99** [comment]
Being a plugin it needs a running installation of [YOURLS](http://yourls.org/) on a webserver with PHP-support. As such it can store uploaded files wherever PHP has access on that server. If your setup meets that requirements, then it should do. The corresponding path within the server's filesystem must be configured as described in readme.md (SHARE_DIR). 

The generated short-links should be accessible on the same server where the file resides, although the link's protocol isn't limited to HTTP(S). If you don't intend to make the files accessible by a short-link you could even set an invalid URL as the configured SHARE_URL. This way you could use the plugin for the sole purpose of uploading files to your PHP-server. Just remember not to publish such invalid short-links.

If you want to serve the files via a different server you can set a corresponding SHARE_URL as the target for the short-links, but you would have to find a way to move or copy the files there.

**Comment by JayHoltslander** [comment]
I'll have to look into this more later. I think it'll require [AWS-CLI](https://aws.amazon.com/cli/) to be installed on the server first.
