### ISSUE TITLE
"Upload failed, sorry! The error was 0"

### ISSUE THREAD

**Issue by alidevs** [fredl99/YOURLS-Upload-and-Shorten#6]
Help please?

**Comment by fredl99** [comment]
Please provide some more information. At least:

- What was the name of the file?
- Which method of filename alteration did you use, if any?
- Does the target folder exist?
- Did it work with another file before?
- What kind of Webserver?
- Which operating system?
- and so on...

I'm always willing to help but it's not possible without any input.

**Comment by alidevs** [comment]
Ubuntu 16.04 and Apache are the only two answers I have xD (Sorry, I'm not an expert)
but I think I have a problem at these lines ..
`define( 'SHARE_URL', 'http://' ); 
define( 'SHARE_DIR', '/etc/apache2/httpd.conf' ); `

**Comment by fredl99** [comment]
> I think I have a problem at these lines

If you already think so then you should have a very close look at the installation steps in readme.md, especially the last line of step 3.

It's your decision if you want to share something in your admin's directory with others, but it's the webserver's decision not to allow someone to overwrite it's configuration file. Beside of that `/etc/apache2/httpd.conf` is a **file**, not a **directory**.

Please read the docs and obtain some basics before opening services on the internet.

**Comment by fredl99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/fredl99/YOURLS-Upload-and-Shorten/projects/1#card-747902](https://trello.com/c/dbLW3OX2/1-https-github-com-fredl99-yourls-upload-and-shorten-projects-1-card-747902)

**Comment by Nickelz** [comment]
"Card Not Found"
[https://puu.sh/tpYCX/8e39b957e9.png](url)

**Comment by fredl99** [comment]
That message shouldn't appear here, sorry. It wasn't meant as a message to you.

My advice to you was already above.

**Comment by fredl99** [comment]
Closed after 3 weeks without user input. 
Obviously not a bug, but rather a configuration error.
Feel free to re-open the issue when you're ready to provide necessary informations.
